### ISSUE TITLE
Dokku installation fails

### ISSUE THREAD

**Issue by jimeh** [rlister/chef-dokku-simple#2]
During first run when the bootstrap.sh script runs, it just ends up dying with printing `apt-get install` output. I believe it's caused by the interactive wizard that the dokku deb package pops up asking about web/console setup.

For the time being I just ran the bootstrap.sh script manually, after which the cookbook works fine to managing SSH keys, plugins etc.

I'm not sure how to solve this myself, as the bootstrap.sh script already passes in `-qq` to apt-get and sets `DEBIAN_FRONTEND` to `noninteractive`.

**Comment by jimeh** [comment]
I should probably point out that I'm using v0.3.22, which uses a debian package to install itself (since v0.3.13) rather than being installed from source.

**Comment by jimeh** [comment]
I just did a bit of digging and came across info about [unattended installation](http://progrium.viewdocs.io/dokku/getting-started/install/debian/) in the dokku docs. When I have some time I'll take a stab at making the necessary changes to get the installation working via the package method :)

**Comment by rlister** [comment]
@jimeh that would be awesome

**Comment by jimeh** [comment]
Tonight I got a first attempt/hack of it seemingly working. I just need to clean up the code a bit, and test it a bit further. So I should have a PR ready for you within a couple of days if real life doesn't get in the way too much... lol

**Comment by rlister** [comment]
Real life ... prevents so much good coding!

**Comment by jimeh** [comment]
Cleaned up the code a bit, but I'm having issues with upgrading dokku. It's looking like it's related to dokku rather this cookbook though, specifically it's post-install script seems to fail when reading debconf settings.

I've reported the issue at progrium/dokku#1387 and gonna dig deeper in the coming days. My current changes are [here](https://github.com/rlister/chef-dokku-simple/compare/master...jimeh:fix-installation-issue) if you're curious.

**Comment by rlister** [comment]
@jimeh Thanks for looking into this, changes look good so far. I've made you a collaborator on the project, so feel free to push fixes :-)

**Comment by jimeh** [comment]
@rlister Oh, sweet, thanks :)

**Comment by jimeh** [comment]
Ok, the upgrading issue actually boils down to plugins with a `install` hook which calls `apt-get`. Since the plugin management part is important, I'm planning to have the cookbook remove all plugins that are configured before performing an upgrade to dokku, and then letting them be reinstalled the usual way again.

**Comment by jimeh** [comment]
Fixed by #4.
